AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy EC2 instances and ALB for Project 1 - Outline of Resources/Parameters

# Need to ask user for name of network stack
Parameters:
  NetworkStackName:
    Type: String
    Description: Project1
Resources:

# Optional BastionHostInstance would go here

WebServerInstance1:
  Type: AWS::EC2::Instance
  Properties:
    ImageId: "ami-015f56077b7f5b83f"
    InstanceType: t2.micro
    KeyName: "project1"
    SubnetId:
      Fn::ImportValue:
        !Sub "${NetworkStackName}-PrivateSubnet1"
    GroupSet:
      Fn::ImportValue:
        !Sub "${NetworkStackName}-WebServerSG"

WebServerInstance2:

ALBListener:

ALBTargetGroup:

ApplicationLoadBalancer:

Outputs:
  ApplicationLoadBalancer:
    Description: URL of the Loadbalancer
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - ApplicationLoadBalancer
          - PublicDnsName