AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Network and Security Groups for Project 1 - Outline of Resources
# This should be all the basic sections needed in Project #1
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: Project1 VPC    
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: Project1 InternetGW
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: 
        Ref: VPC
      InternetGatewayId: 
        Ref: InternetGateway
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.0/24
      VpcId: 
        Ref: VPC
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: Name
        Value: "Public Subnet 1"
  PublicSubnet2:
    Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: 10.0.2.0/24
        VpcId: 
          Ref: VPC
      AvailabilityZone: "us-east-1b"
      Tags:
      - Key: Name
        Value: "Public Subnet 2"
  PrivateSubnet1:
        Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: 10.0.3.0/24
        VpcId: 
          Ref: VPC
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: Name
        Value: "Private Subnet 1"
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: 10.0.4.0/24
        VpcId: 
          Ref: VPC
      AvailabilityZone: "us-east-1b"
      Tags:
      - Key: Name
        Value: "Private Subnet 2"
  PublicRouteTable:
    Type: AWS::EC2::Routetable
    Properties:
      VpcId:
        Ref: VPC
      Tags: 
      - Key: Name
        Value: Public Route Table
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId:
        Ref: PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway
  PublicSubnetRouteTableAssociation1:

  PublicSubnetRouteTableAssociation2:

  ALBSecurityGroup:

  WebInstanceSecurityGroup:

  # Optional BastionSercurityGroup if you build a Bastion Host

Outputs:
# This is an example of the complete YAML code for outputting the VPC information and also exporting the VPC ID for use
# by another template
  VPC:
    Description: VPC
    Value:
      Ref: VPC
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-VPCId"
  PrivateSubnet1:

  PrivateSubnet2:

  PublicSubnet1:

  PublicSubnet2:

  WebInstanceSecurityGroup:

  ALBSecurityGroup:
